# This is a basic workflow to help you get started with Actions

on:
  release:
    types: [created]

name: Release workflow

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Install dependencies
      uses: php-actions/composer@v4
      with:
        command: global require humbug/box
    - name: build 
      run: box compile
    - name: Upload the phar
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '/bin/*.phar'
